'use client'

import { useState, useRef, useEffect, useId } from 'react'
import { usePipelineState } from '@/store'
import { usePipeline } from '@/hooks/usePipeline'
import { cn } from '@/lib/utils'

export function FileGatePanel() {
  const { currentFilename, currentFileCode, currentFileIndex, totalFiles, phase, project } = usePipelineState()
  const { acceptFile, submitFileFeedback } = usePipeline()

  const [feedback,     setFeedback]     = useState('')
  const [sending,      setSending]      = useState(false)
  const [accepting,    setAccepting]    = useState(false)
  const [error,        setError]        = useState<string | null>(null)
  const [displayCode,  setDisplayCode]  = useState(currentFileCode ?? '')
  const [lineCount,    setLineCount]    = useState(0)
  const [originalCode, setOriginalCode] = useState(currentFileCode ?? '')
  const [reverted,     setReverted]     = useState(false)
  // 'primary' = coder (default), 'reviewer' = alternative model
  const [modelRole, setModelRole]       = useState<'primary' | 'reviewer'>('primary')
  const [lastModelId, setLastModelId]   = useState<string | null>(null)
  const textareaRef = useRef<HTMLTextAreaElement>(null)
  const labelId     = useId()

  useEffect(() => {
    const code = currentFileCode ?? ''
    setDisplayCode(code)
    setOriginalCode(code)
    setLineCount(code ? code.split('\n').length : 0)
    setFeedback('')
    setError(null)
    setReverted(false)
    setModelRole('primary')
    setLastModelId(null)
  }, [currentFileCode, currentFilename])

  if (phase !== 'phase3_file_gate' || !currentFilename) return null

  const isLast         = currentFileIndex >= totalFiles - 1
  const fileNumber     = currentFileIndex + 1
  const parts          = currentFilename.split('/')
  const basename       = parts.pop() ?? currentFilename
  const dirPrefix      = parts.length > 0 ? parts.join('/') + '/' : ''
  const ext            = basename.split('.').pop() ?? ''
  const primaryModel   = project?.primaryModelId  ?? 'coder'
  const reviewerModel  = project?.reviewerModelId ?? 'reviewer'
  const activeModel    = modelRole === 'primary' ? primaryModel : reviewerModel
  const hasChanged     = displayCode !== originalCode

  async function handleSend() {
    if (!feedback.trim() || !currentFilename || !displayCode) return
    setSending(true)
    setError(null)
    setReverted(false)
    try {
      const result = await submitFileFeedback(currentFilename, displayCode, feedback.trim(), modelRole)
      setDisplayCode(result.code)
      setLineCount(result.code ? result.code.split('\n').length : 0)
      setLastModelId(result.modelId)
      setFeedback('')
      textareaRef.current?.focus()
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Regeneration failed')
    } finally {
      setSending(false)
    }
  }

  async function handleAccept() {
    if (!currentFilename) return
    setAccepting(true)
    setError(null)
    try {
      await acceptFile(currentFilename, displayCode)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to save file')
      setAccepting(false)
    }
  }

  function handleRevert() {
    setDisplayCode(originalCode)
    setLineCount(originalCode ? originalCode.split('\n').length : 0)
    setReverted(true)
    setLastModelId(null)
    setTimeout(() => setReverted(false), 2000)
  }

  return (
    <div className="flex h-full flex-col bg-zinc-950">

      {/* ── Header ─────────────────────────────────────────────────────── */}
      <div className="shrink-0 border-b border-zinc-800 px-6 pt-5 pb-4 space-y-3">

        {/* File path hero */}
        <div className="space-y-1">
          <div className="flex items-baseline gap-0 font-mono leading-none min-w-0">
            {dirPrefix && (
              <span className="text-sm text-zinc-500 shrink-0">{dirPrefix}</span>
            )}
            <span className="text-sm font-semibold text-indigo-300 truncate">{basename}</span>
            <span className="ml-2 shrink-0 text-[10px] text-zinc-700 self-center">
              {lineCount} lines
            </span>
          </div>
          <div className="flex items-center gap-2 flex-wrap">
            {ext && (
              <span className="rounded-sm border border-indigo-800/40 bg-indigo-950/30 px-1.5 py-0.5 font-mono text-[9px] text-indigo-500 uppercase tracking-wider">
                {ext}
              </span>
            )}
            {lastModelId && !hasChanged && (
              <span className="font-mono text-[10px] text-zinc-600">
                Last regenerated by <span className="text-zinc-400">{lastModelId}</span>
              </span>
            )}
            {hasChanged && !sending && (
              <button
                onClick={handleRevert}
                className="font-mono text-[10px] text-zinc-600 hover:text-zinc-400 transition-colors underline underline-offset-2"
              >
                {reverted ? '✓ reverted' : 'revert to original'}
              </button>
            )}
            {!hasChanged && !lastModelId && (
              <span className="text-[10px] text-zinc-600">
                Review before saving · send feedback or continue
              </span>
            )}
          </div>
        </div>

        {/* Progress dots */}
        <div
          className="flex items-center gap-2"
          role="status"
          aria-live="polite"
          aria-label={`File ${fileNumber} of ${totalFiles}`}
          data-testid="file-progress"
        >
          <div className="flex items-center gap-1" aria-hidden>
            {Array.from({ length: totalFiles }).map((_, i) => (
              <span
                key={i}
                title={
                  i < currentFileIndex  ? `File ${i + 1}: accepted` :
                  i === currentFileIndex ? `File ${i + 1}: current` :
                                           `File ${i + 1}: pending`
                }
                className={cn(
                  'font-mono text-xs leading-none transition-colors',
                  i < currentFileIndex  ? 'text-indigo-500' :
                  i === currentFileIndex ? 'text-indigo-300' :
                                           'text-zinc-700',
                )}
              >
                {i < currentFileIndex ? '●' : i === currentFileIndex ? '◉' : '○'}
              </span>
            ))}
          </div>
          <span className="font-mono text-[10px] text-zinc-600">
            {fileNumber} / {totalFiles}
          </span>
        </div>
      </div>

      {/* ── Code viewer or loading state ────────────────────────────────── */}
      {accepting ? (
        <div className="flex flex-1 items-center justify-center">
          <span className="font-mono text-xs text-zinc-600 animate-pulse">
            {isLast ? 'Saving final file…' : 'Saving, loading next file…'}
          </span>
        </div>
      ) : sending ? (
        <div className="flex flex-1 flex-col items-center justify-center gap-4">
          <div className="space-y-1.5 text-center">
            <p className="font-mono text-xs text-indigo-400 animate-pulse">Regenerating…</p>
            <p className="font-mono text-[10px] text-zinc-600">
              {activeModel} is updating {basename}
            </p>
          </div>
          {feedback && (
            <div className="mx-8 rounded-sm border border-zinc-800 bg-zinc-900/60 px-4 py-3 max-w-md w-full">
              <p className="font-mono text-[9px] uppercase tracking-widest text-zinc-600 mb-1">Your instruction</p>
              <p className="font-mono text-xs text-zinc-300">{feedback}</p>
            </div>
          )}
        </div>
      ) : (
        <div className="flex flex-1 overflow-hidden" data-testid="file-code-viewer">
          <div className="w-1 shrink-0 bg-indigo-600/80" aria-hidden />
          <pre className="flex-1 overflow-auto px-5 py-4 font-mono text-xs leading-relaxed text-zinc-200 bg-zinc-950 selection:bg-indigo-900/40">
            {displayCode}
          </pre>
        </div>
      )}

      {/* ── Feedback + model selector + actions ─────────────────────────── */}
      <div className="shrink-0 border-t border-zinc-800 bg-zinc-900/40">

        {error && (
          <div className="border-b border-red-900/40 px-6 py-2" role="alert">
            <p className="font-mono text-xs text-red-400">{error}</p>
          </div>
        )}

        <div className="px-6 pt-4 pb-4 space-y-3">

          {/* Model selector */}
          <div className="flex items-center gap-2">
            <span className="font-mono text-[10px] text-zinc-600 shrink-0">Regenerate with:</span>
            <div className="flex items-center gap-1">
              <button
                onClick={() => setModelRole('primary')}
                className={cn(
                  'rounded-sm border px-2 py-0.5 font-mono text-[10px] transition-colors',
                  modelRole === 'primary'
                    ? 'border-indigo-700 bg-indigo-950/40 text-indigo-300'
                    : 'border-zinc-800 text-zinc-600 hover:border-zinc-700 hover:text-zinc-400',
                )}
                title="Use the original coder model (default)"
              >
                {primaryModel}
              </button>
              {reviewerModel !== primaryModel && (
                <button
                  onClick={() => setModelRole('reviewer')}
                  className={cn(
                    'rounded-sm border px-2 py-0.5 font-mono text-[10px] transition-colors',
                    modelRole === 'reviewer'
                      ? 'border-zinc-500 bg-zinc-800/40 text-zinc-200'
                      : 'border-zinc-800 text-zinc-600 hover:border-zinc-700 hover:text-zinc-400',
                  )}
                  title="Use the reviewer model instead"
                >
                  {reviewerModel}
                </button>
              )}
            </div>
          </div>

          {/* Feedback textarea */}
          <div>
            <label id={labelId} className="sr-only">
              Feedback for {currentFilename} — describe what to add, remove, or change
            </label>
            <div className="flex items-start gap-2">
              <span className="shrink-0 font-mono text-xs text-zinc-600 mt-2 select-none" aria-hidden>$</span>
              <textarea
                ref={textareaRef}
                value={feedback}
                onChange={e => setFeedback(e.target.value)}
                onKeyDown={e => {
                  if (e.key === 'Enter' && (e.metaKey || e.ctrlKey) && feedback.trim()) {
                    e.preventDefault()
                    void handleSend()
                  }
                }}
                placeholder={`Tell the coder what to change in ${basename}…  (Ctrl/⌘↵ to send)`}
                disabled={sending || accepting}
                rows={2}
                aria-labelledby={labelId}
                aria-disabled={sending || accepting}
                className="flex-1 resize-none rounded-sm border border-zinc-800 bg-zinc-900 px-3 py-2 font-mono text-xs text-zinc-200 placeholder-zinc-700 focus:border-zinc-600 focus:outline-none transition-colors disabled:opacity-40"
              />
              <button
                onClick={handleSend}
                disabled={!feedback.trim() || sending || accepting}
                aria-label="Send feedback and regenerate this file"
                className={cn(
                  'shrink-0 self-end rounded-sm border px-3 py-2 font-mono text-xs transition-colors',
                  feedback.trim() && !sending && !accepting
                    ? 'border-zinc-600 text-zinc-300 hover:border-zinc-400 hover:text-zinc-100'
                    : 'border-zinc-800 text-zinc-700 cursor-not-allowed',
                )}
              >
                ↵
              </button>
            </div>
          </div>

          {/* Continue / Complete */}
          <button
            onClick={handleAccept}
            disabled={sending || accepting}
            data-testid={isLast ? 'complete-button' : 'continue-button'}
            aria-label={isLast ? 'Accept final file and complete pipeline' : `Accept ${basename} and review next file`}
            className={cn(
              'w-full rounded-sm py-2.5 font-mono text-xs font-semibold tracking-wide transition-colors',
              !sending && !accepting
                ? isLast
                  ? 'bg-indigo-600 text-white hover:bg-indigo-500'
                  : 'border border-zinc-600 text-zinc-200 hover:border-indigo-600/60 hover:text-zinc-100 hover:bg-indigo-950/20'
                : 'border border-zinc-800 text-zinc-700 cursor-not-allowed',
            )}
          >
            {accepting ? 'Saving…' : isLast ? '✓  Complete' : 'Continue  →'}
          </button>
        </div>
      </div>
    </div>
  )
}
